#cloud-config
package_update: true
package_upgrade: true
runcmd:
  - sudo apt update && sudo apt upgrade -y
  - sudo apt install openssh-server -y
  - sudo systemctl enable ssh
  - sudo systemctl start ssh

  - sudo apt install -y software-properties-common unzip
  - sudo add-apt-repository multiverse
  - sudo dpkg --add-architecture i386
  - sudo apt update && sudo apt install -y steamcmd

  # Create a dedicated user for the Valheim server
  - sudo useradd -m -s /bin/bash valheim
  - echo 'valheim ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/valheim

  # Switch to the Valheim user
  - sudo -u valheim mkdir -p /home/valheim/server
  - sudo -u valheim steamcmd +login anonymous +force_install_dir /home/valheim/server +app_update 896660 validate +quit

  # Create a Valheim startup script
  - echo '#!/bin/bash
    cd /home/valheim/server
    ./valheim_server.x86_64 -name "My Valheim Server" -port 2456 -world "MyWorld" -password "YourStrongPassword" -public 1' | sudo tee /home/valheim/start_valheim.sh
  - sudo chmod +x /home/valheim/start_valheim.sh

  # Set up a systemd service to manage the Valheim server
  - echo '[Unit]
    Description=Valheim Server
    After=network.target

    [Service]
    Type=simple
    Restart=always
    User=valheim
    WorkingDirectory=/home/valheim/server
    ExecStart=/home/valheim/start_valheim.sh
    ExecStop=/bin/kill -2 $MAINPID
    RestartSec=10

    [Install]
    WantedBy=multi-user.target' | sudo tee /etc/systemd/system/valheim.service

  # Enable and start the Valheim server
  - sudo systemctl daemon-reload
  - sudo systemctl enable valheim.service
  - sudo systemctl start valheim.service

  # Configure firewall to allow Valheim connections
  - sudo ufw allow 2456/udp
  - sudo ufw allow 2457/udp
  - sudo ufw allow 2458/udp
  - sudo ufw enable